### ISSUE TITLE
Investigate spotify docker client to replace own docker client

### ISSUE THREAD

**Issue by wouterd** [wouterd/docker-maven-plugin#17]
https://github.com/spotify/docker-client

**Comment by icksa** [comment]
I was using the spotify docker-maven-plugin for a while before switching to yours. The spotify plugin had one serious issue for our environment that led us to switch. When doing an "ADD" command in the dockerfile, the spotify plugin always broke the cache, whereas your plugin preserves the cache.

I believe the reason was that when a file was added using the spotify plugin, the plugin would copy the file, thus changing its timestamp. This meant that every build resulted in generating completely new docker images - this consumes lots of disk space and was significantly increasing our build times.

With your plugin, I have extremely good caching and our build times are very fast - unless the underlying files actually change.

Thanks, and please keep up the great work!

**Comment by wouterd** [comment]
Thanks for the kind words!

And thanks for the heads up. I'll keep it in mind for the spotify "driver". I prefer that this plugin stays as close to a "docker wrapper" as possible, without too much of it's own magic that happens.
Notable exception would be wiring integration tests together. :-)
